### ISSUE TITLE
Allowed categories needs to be updated

### ISSUE THREAD

**Issue by darvark** [thxo/cabrillo#13]
Hi,
Latest version on library is not updated to allowed categories and/or types of operation. 

`Got DISTRIBUTED for category_station but expecting one of ['FIXED', 'MOBILE', 'PORTABLE', 'ROVER', 'ROVER-LIMITED', 'ROVER-UNLIMITED', 'EXPEDITION', 'HQ', 'SCHOOL', 'EXPLORER'].`

Please update allowed header values.

**Comment by thxo** [comment]
Thank you. I'll do a pass over the changelog. In the meantime you can set `check_categories=False` where you to your parsing.

**Comment by thxo** [comment]
Fixed in https://github.com/thxo/cabrillo/releases/tag/v0.2.0, now also on PyPI.
