### ISSUE TITLE
Time for 0.1 ?

### ISSUE THREAD

**Issue by kareiva** [thxo/cabrillo#7]
Maybe it is time to look at the possibility to merge the changes by @aknrdureegaesr and maybe few more for a new release?

If @thxo approves I can try to build a meaningful PR

**Comment by thxo** [comment]
Hi! You're right that it's been a while since there has been a release. I will look into it!

**Comment by thxo** [comment]
https://github.com/thxo/cabrillo/releases/tag/v0.1.0
https://pypi.org/project/cabrillo/0.1.0/ :)

**Comment by kareiva** [comment]
Thanks, I just checked that all the changes by @aknrdureegaesr are already in - great! Appreciate the merge.
